Dev
Fillinius/R-M-with-Vite-and-TS pull request #1
Opened 2024-08-13 16:39 UTC by Fillinius

2025-01-23 00:42 UTC, taraswww777 requested changes

2025-01-23 00:42 UTC, taraswww777 commented on package.json
> +    "@emotion/react": "^11.13.0",
### Версии зависимостей в package.json

Лучше указывать точные версии зависимостей без символов `~` и `^`.
Например так: `"lodash":"4.17.21"`
Команда для установки `npm i lodash -ED`

2025-01-23 00:42 UTC, taraswww777 commented on package.json
>    "devDependencies": {
### Куда ставить зависимость в `devDependencies` или `dependencies`

Ключевая разница между `devDependencies` и `dependencies` заключается в следующем.

- `dependencies`
  - Нужны после сборки, для работы приложения
  - Установятся тогда когда кто-то наш код подключит в зависимости
  - На фронте крайне редко нужны
- `devDependencies`

  - Нужны только на этапе разработки

  На большинстве FE приложений и библиотек, которые как-то компилируются, можно спокойно использовать `devDependencies`

2025-01-23 00:42 UTC, taraswww777 commented on src/entities/home.tsx
> +export default Home
## Именованные экспорты

Предпочтительнее использовать экспорты.
Например:

```tsx
export const App = () => (<div> I'm App </div>);
```

default лучше оставить только для исключительных случаем например:

- React.lazy - <https://react.dev/reference/react/lazy>
- и прочее

2025-01-23 00:42 UTC, taraswww777 commented on src/entities/home.tsx
> +const Home = () => {
`Home` это не просто entities, это pages, а значит должен находиться в папке `src/pages` и иметь название `HomePage`.

В файле `src/pages/index.ts`  нужно

```tsx
export const HomePage = lazy(() => import('./HomePage.tsx'))
````

2025-01-23 00:42 UTC, taraswww777 commented on src/app/App.tsx
> +const Heroes = lazy(() => import('../entities/ui/heroes.tsx'))
Все компоненты которые которые являются по сути страницами, то они должны зазывать `HeroesPage`.

2025-01-23 00:42 UTC, taraswww777 commented on src/app/App.tsx
> +const Heroes = lazy(() => import('../entities/ui/heroes.tsx'))
Нет смысла делать lazy import в каждом месте импорта, это лучше делать в `src/pages/index.ts`

2025-01-23 00:42 UTC, taraswww777 commented on src/entities/page/episode/episodiesList.tsx
> +const EpisodiesList = ({
Както так по идее должен начинаться компонент

```tsx
import { VFC } from 'react';

interface EpisodiesListProps {
  data: DataFetchProp[]
  lastNodeRef: React.RefObject<HTMLElement>
}

export  const EpisodiesList: VFC<EpisodiesListProps> = ({ data, lastNodeRef }) => {
 ...
}

```

2025-01-23 00:42 UTC, taraswww777 commented on src/entities/page/episode/episodiesList.tsx
> +                <Link to={pathname + '/' + item.id} className="card-link">
Ссылку надо писать полностью, чтобы мы могли на любой странице вывести  список эпизодов.
Поэтому использование pathname  тут не уместно. Логичнее написать вот так:

```tsx
<Link to={`/episode/${item.id}`} className="card-link">
```

2025-01-23 00:44 UTC, taraswww777 commented on src/entities/page/episode/episodiesList.tsx
> +const EpisodiesList = ({
Пропсы компонента нужно описывать в interface

2025-01-23 00:57 UTC, taraswww777 approved these changes

2025-01-23 00:57 UTC, taraswww777 commented on src/entities/page/heroes/heroesList.tsx
> +  data: DataFetchProp[]
https://github.com/Fillinius/R-M-with-Vite-and-TS/pull/1/files#r1926196334

2025-01-23 00:57 UTC, taraswww777 commented on src/entities/page/heroes/heroesList.tsx
> +                <Link to={pathname + '/' + item.id} className="card-link">
https://github.com/Fillinius/R-M-with-Vite-and-TS/pull/1/files#r1926198253

2025-01-23 00:57 UTC, taraswww777 commented on src/entities/ui/episodies.tsx
> +        (data.length === 0 ? (
Вот так можно сократить

```ts
(data.length  ? (<EpisodiesList data={data} lastNodeRef={lastNodeRef} />) : 'Список пуст' )
```

2025-01-23 00:57 UTC, taraswww777 commented on src/entities/ui/heroes.tsx
> +    setPageNumber((p) => (p < 42 ? Number(p) + 2 : p))
Магические числа это плохая практика, подробнее по ссылкам ниже

https://code-basics.com/ru/languages/javascript/lessons/magic-numbers

https://dev.to/ruben_alapont/magic-numbers-and-magic-strings-its-time-to-talk-about-it-ci2

2025-01-23 00:57 UTC, taraswww777 commented on src/feature/registration/Registation.tsx
> +const INITIALSTATEREG = {
Где типизация?

2025-01-23 00:57 UTC, taraswww777 commented on src/feature/registration/Registation.tsx
> +  const [data, setData] = React.useState(INITIALSTATEREG)
Где типизация?

2025-01-23 00:57 UTC, taraswww777 commented on src/index.css
> +.header {
Используется MUI может им можно решить задачу по стилизации?
в tailwind для этого есть `tailwind.config.ts`

2025-01-23 00:57 UTC, taraswww777 commented on src/path/internalPaths.ts
> +export const INTERNALPATH = {
Нужно разделать UI и API url

Чуть подробнее написано тут https://taraswww777.dev/articles/2025-01-11-how-make-iu-links

2025-01-24 09:27 UTC, Fillinius commented on package.json
> +    "@emotion/react": "^11.13.0",
Исправил, спасибо за совет

2025-01-24 09:37 UTC, Fillinius commented on package.json
>    "devDependencies": {
принято

2025-01-24 10:15 UTC, Fillinius commented on src/entities/home.tsx
> +export default Home
Исправил

2025-01-24 10:35 UTC, Fillinius commented on src/entities/home.tsx
> +const Home = () => {
ok

2025-01-24 10:38 UTC, Fillinius commented on src/app/App.tsx
> +const Heroes = lazy(() => import('../entities/ui/heroes.tsx'))
-

2025-01-24 10:50 UTC, Fillinius commented on src/entities/page/episode/episodiesList.tsx
> +                <Link to={pathname + '/' + item.id} className="card-link">
ок

2025-01-24 11:03 UTC, Fillinius commented on src/entities/ui/episodies.tsx
> +        (data.length === 0 ? (
спасибо

2025-01-24 11:11 UTC, Fillinius commented on src/entities/ui/episodies.tsx
> +        (data.length === 0 ? (
поставил, заметку

2025-01-24 11:30 UTC, Fillinius commented on src/entities/ui/heroes.tsx
> +    setPageNumber((p) => (p < 42 ? Number(p) + 2 : p))
Спасибо, за статью отдельное спасибо, полез в код, и сам не помню что это  ,были за числа.
Исправил

2025-01-24 11:35 UTC, Fillinius commented on src/index.css
> +.header {
Плохо разобрался в этой теме, буду разбираться, позже попробую исправить

2025-01-24 12:26 UTC, Fillinius commented on src/path/internalPaths.ts
> +export const INTERNALPATH = {
Полезно, спасибо, исправил.

2025-01-24 12:52 UTC, merged